### ISSUE TITLE
w20-business-theme not found from w20 yeoman generator

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/generator-w20#10]
_From @evinel on March 14, 2016 23:2_

bower install can not resolve  w20-business-theme ^1.2 from  W20 yeoman generator

Error : 
bower w20-business-theme#^1.2     ENORESTARGET No tag found that was able to satisfy ^1.2

_Copied from original issue: seedstack/w20#65_

**Comment by adrienlauer** [comment]
Hi @evinel,

I committed a fix for your issue but we need to wait until @kavi87 publishes it on NPM. He is unvailable for one or two days but we will release the generator asap.

Thanks for reporting the issue.

**Comment by adrienlauer** [comment]
@evinel: This fix has been released in version 1.2.1 of the generator.

**Comment by evinel** [comment]
Thx Mec :). 
Surtout que je l'utilise :D

@++

Envoyé de mon iPhone
